# Triggered by pull request or push to develop branch
# Test TypeScript rest connector.
name: rest 3.0 on push&pull

on:
  push:
    branches: ['3.0']
  pull_request:
    branches: ['3.0'] 

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]   
    steps:

    - name: Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt-get install -y python3 python3-pip python-is-python3

    - name: Checkout TDengine
      uses: actions/checkout@v3
      with:
          fetch-depth: 1
          repository: 'taosdata/TDengine'
          path: 'TDengine'
          ref: '3.0'
          submodules: 'recursive'

    - name: Build TDengine 3.0
      run: |
          cd TDengine
          mkdir debug
          cd debug
          cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=false -DBUILD_HTTP=false
          make -j8
          sudo make install
          
    - name: start taosd
      run: |
        nohup sudo taosd &

    - name: start taosadapter
      run: |
        nohup sudo taosadapter &

    - name: checkout nodejs 3.0
    - uses: actions/checkout@v3
      with:
          path : "node-taos"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: test WebSocket
      working-directory: node-taos/WebSocket
      run: |
        ls -al
        npm install
        npm run example

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
        files: coverage/lcov.info
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}